//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;

[assembly: AssemblyDescription("Report generation command-line tool for Aras")]
[assembly: AssemblyProduct("Innovator.ReportEngine")]
[assembly: AssemblyVersion("1.0.6788.28426")]
[assembly: AssemblyFileVersion("1.0.6788.28426")]

